services:
  agendarcita:
    build: ./AgendarCita
    ports:
      - "8083:4000"
    env_file:
      - ./.env
    networks:
      - red-apis

  historiamedica:
    build: ./HistoriaClinica
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - red-apis

  doctores:
    build: ./Doctores
    ports:
      - "8081:3000"
    env_file:
      - ./.env
    networks:
      - red-apis

  pacientes:
    build: ./Pacientes
    ports:
      - "8082:8000"
    env_file:
      - ./.env
    networks:
      - red-apis
networks:
  red-apis:
    external: true
