services:
  agendarcita:
    build: ./AgendarCita
    ports:
      - "8083:4000"
    env_file:
      - ./.env
    networks:
      - red_apis

  historiamedica:
    build: ./HistoriaClinica
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - red_apis

  doctores:
    build: ./Doctores
    ports:
      - "8081:3000"
    env_file:
      - ./.env
    networks:
      - red_apis

  pacientes:
    build: ./Pacientes
    ports:
      - "8082:8000"
    env_file:
      - ./.env
    networks:
      - red_apis
networks:
  red_apis:
    external: true
